# Constraint Satisfaction Problems

As we saw, many AI problems can be modelled as a graph of states that a problem can be in. We then use a search algorithm to find a path in this graph that leads to the solution. One type of problems that can be solved in this manner are Constraint Satisfaction Problems. Constraints are basically conditions that cannot be violated during the process of solving the problem. When we arrive at the final solution, the states of the variables must obey all the constraints. 

Now, let us try to apply this to some real world problems. We will start with two relatively simple examples.

## 1. Hello World

We could try to implement the search algorithms ourselves (using our knowledge of graphs), but since this would be a little difficult, we will be using a library. Let us first use the python library *python-constraint* to solve a very basic constraint problem.

First install the library using following command:

In [1]:
pip install python-constraint

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
# we will use the python range function

for i in range(5):
    print(i)

0
1
2
3
4


Now define a constraint problem with two variables within a specific range.

In [3]:
from constraint import *
problem = Problem()

problem.addVariable('a', range(8))
problem.addVariable('b', range(12))

Add the constraint the variables must obey.

In [4]:
# the lambda expression states that for every solution b must be two times a
problem.addConstraint(lambda a, b: a * 2 == b)

Let's see what solutions can be found. Check the results! Are the constraints satisfied?

In [5]:
solutions = problem.getSolutions()
print (solutions)

[{'a': 5, 'b': 10}, {'a': 4, 'b': 8}, {'a': 3, 'b': 6}, {'a': 2, 'b': 4}, {'a': 1, 'b': 2}, {'a': 0, 'b': 0}]


## 2. Numbers and values

One more simple example before getting to the real stuff. We will be using a package called *simpleai*. It contains various routines that are useful in building solutions using heuristic search techniques.

First install the library using following command:

In [6]:
pip install simpleai

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
# we will use the python set function to remove duplicated values in a collection of values

print(set({ 1, 2, 3, 1, 2, 4, 3}))

{1, 2, 3, 4}


We will first import the necessary classes and define the problem.

In [8]:
from simpleai.search import CspProblem, backtrack

# we will try to find the value of four variables named number1, number2, number3, number4
variables = ('number1', 'number2', 'number3', 'number4')

# the list of values that each variable can take
domains = {
    'number1': [1, 2, 3],
    'number2': [1, 3],
    'number3': [2, 4],
    'number4': [2, 3, 4],
}

# define all the constraints, a constraint is a function with two parameters: variables and values
# the constraint returns true if the values obey the constraint, false otherwise

# a constraint that expects all the different variables to have different values
def constraint_unique(variables, values):
    # check if all the values are unique
    if len(values) == len(set(values)): # remove repeated values and count
        return True
    else:
        return False

# a constraint that expects the first variable to be bigger than the second
def constraint_bigger(variables, values):
    return values[0] > values[1] # short notation (if-then-else is not necessary)

# a constraint that expects two variables to be one odd and the other even
def constraint_odd_even(variables, values):
    if values[0] % 2 == 0:
        return values[1] % 2 == 1  # first even, expect second to be odd
    else:
        return values[1] % 2 == 0  # first odd, expect second to be even

Define the constraints for various scenarios. In this case, we specify three constraints as follows:
    
1. number1, number2 and number3 should be different values
2. number3 should be bigger than number2
3. if number1 is odd, then number4 value should be even and vice versa

And finaly search for a solution.

In [9]:
constraints = [
    (('number1', 'number2', 'number3'), constraint_unique),
    (('number3', 'number2'), constraint_bigger),
    (('number1', 'number4'), constraint_odd_even),
    (('number4', 'number1'), constraint_odd_even),
]

problem = CspProblem(variables, domains, constraints)

output = backtrack(problem)
print('\nSolutions:', output)


Solutions: {'number1': 1, 'number2': 3, 'number3': 4, 'number4': 2}


You can check the __domains__ and the __constraints__ to see if the solutions satisfy all those constraints. By the way, there is more then one solution, the search algorithm stops after finding the first one.

## 3. Sudoku - Exercise

Can you try to solve the following simplified sudoku puzzle? The aim is to fill the grid so that each row, column and box contains the same numbers (1 to 4).

<img src="./resources/sudoku.png"  style="height: 200px"/>

With a little more programming effort, you could use the same technique to solve a real sudoku (if you don't know what to do this evening).

In [10]:
from simpleai.search import CspProblem, backtrack

grid = [
    [0,0,4,3],
    [0,0,0,0],
    [0,0,0,0],
    [2,3,0,0]
]
constraints = [
    ((grid[0][0],grid[0][1],grid[0][2],grid[0][3]),constraint_unique),
    ((grid[1][0],grid[1][1],grid[1][2],grid[1][3]),constraint_unique),
    ((grid[2][0],grid[2][1],grid[2][2],grid[2][3]),constraint_unique),
    ((grid[3][0],grid[3][1],grid[3][2],grid[3][3]),constraint_unique),
    ((grid[0][0],grid[0][1],grid[1][0],grid[1][1]),constraint_unique),
    ((grid[0][2],grid[0][3],grid[1][2],grid[1][3]),constraint_unique),
    ((grid[2][0],grid[2][1],grid[3][0],grid[3][1]),constraint_unique),
    ((grid[2][2],grid[2][3],grid[3][2],grid[3][3]),constraint_unique),
]

domains = {
    grid[0][0]: [1,2,3,4],
    grid[0][1]: [1,2,3,4],
    grid[0][2]: [1,2,3,4],
    grid[0][3]: [1,2,3,4],
    grid[1][0]: [1,2,3,4],
    grid[1][1]: [1,2,3,4],
    grid[1][2]: [1,2,3,4],
    grid[1][3]: [1,2,3,4],
    grid[2][0]: [1,2,3,4],
    grid[2][1]: [1,2,3,4],
    grid[2][2]: [1,2,3,4],
    grid[2][3]: [1,2,3,4],
    grid[3][0]: [1,2,3,4],
    grid[3][1]: [1,2,3,4],
    grid[3][2]: [1,2,3,4],
    grid[3][3]: [1,2,3,4],
}

problem = CspProblem(grid, domains, constraints)

output = backtrack(problem)
print(output)




TypeError: unhashable type: 'list'

In [11]:
from simpleai.search import CspProblem, backtrack
import numpy as np

grid = [
    [0,0,4,3],
    [0,0,0,0],
    [0,0,0,0],
    [2,3,0,0]
]

def possible(y,x,n):
    global grid
    for i in range(0,4):
        if grid[y][i]==n:
            return False
    for i in range(0,4):
        if grid[i][x] == n:
            return False
    x0=(x//2)*2
    y0=(y//2)*2
    for i in range(0,2):
        for j in range(0,2):
            if grid[y0+i][x0+j] == n:
                return False
    return True

# print(np.matrix(grid))

# print(possible(0,0,4))

def solve():
    global grid
    for y in range(4):
        for x in range(4):
            if grid[y][x] == 0:
                for n in range(1,5):
                    if possible(y,x,n):
                        grid[y][x] = n
                        solve()
                        grid[y][x] = 0
                return
    print(np.matrix(grid))
    input('More?')

solve()



[[1 2 4 3]
 [3 4 2 1]
 [4 1 3 2]
 [2 3 1 4]]


In [1]:
from simpleai.search import CspProblem, backtrack
import numpy as np

def constraint_unique(variables, values):
    # check if all the values are unique
    if len(values) == len(set(values)): # remove repeated values and count
        return True
    else:
        return False

grid = [
    [0,0,4,3],
    [0,0,0,0],
    [0,0,0,0],
    [2,3,0,0]
]

grid2 = ('x0y0','x0y1','x0y2','x0y3',
         'x1y0','x1y1','x1y2','x1y3',
         'x2y0','x2y1','x2y2','x2y3',
         'x3y0','x3y1','x3y2','x3y3')

domains2 = {
    'x0y0': [1,2,3,4],
    'x0y1': [1,2,3,4],
    'x0y2': [3],
    'x0y3': [4],
    'x1y0': [1,2,3,4],
    'x1y1': [1,2,3,4],
    'x1y2': [1,2,3,4],
    'x1y3': [1,2,3,4],
    'x2y0': [1,2,3,4],
    'x2y1': [1,2,3,4],
    'x2y2': [1,2,3,4],
    'x2y3': [1,2,3,4],
    'x3y0': [2],
    'x3y1': [3],
    'x3y2': [1,2,3,4],
    'x3y3': [1,2,3,4]
}

constraints2 = [
    (('x0y0', 'x0y1', 'x0y2','x0y3'), constraint_unique),
    (('x1y0', 'x1y1', 'x1y2','x1y3'), constraint_unique),
    (('x2y0', 'x2y1', 'x2y2','x2y3'), constraint_unique),
    (('x3y0', 'x3y1', 'x3y2','x3y3'), constraint_unique),

    (('x0y0', 'x1y0', 'x2y0','x3y0'), constraint_unique),
    (('x0y1', 'x1y1', 'x2y1','x3y1'), constraint_unique),
    (('x0y2', 'x1y2', 'x2y2','x3y2'), constraint_unique),
    (('x0y3', 'x1y3', 'x2y3','x3y3'), constraint_unique),

    (('x0y0', 'x0y1', 'x1y0','x1y1'), constraint_unique),
    (('x2y0', 'x2y1', 'x3y0','x3y1'), constraint_unique),
    (('x0y2', 'x0y3', 'x1y2','x1y3'), constraint_unique),
    (('x2y2', 'x2y3', 'x3y2','x3y3'), constraint_unique),
]

problem = CspProblem(grid2, domains2, constraints2)

output = backtrack(problem)
print(output)

grid[0][0] = output['x0y0']
grid[0][1] = output['x0y1']
grid[0][2] = output['x0y2']
grid[0][3] = output['x0y3']

grid[1][0] = output['x1y0']
grid[1][1] = output['x1y1']
grid[1][2] = output['x1y2']
grid[1][3] = output['x1y3']

grid[2][0] = output['x2y0']
grid[2][1] = output['x2y1']
grid[2][2] = output['x2y2']
grid[2][3] = output['x2y3']

grid[3][0] = output['x3y0']
grid[3][1] = output['x3y1']
grid[3][2] = output['x3y2']
grid[3][3] = output['x3y3']

print(np.matrix(grid))

for x in range(4):
    for y in range(4):
        grid[x][y] = output['x'+str(x)+'y'+str(y)]
print(np.matrix(grid))

{'x0y0': 1, 'x0y1': 2, 'x0y2': 3, 'x0y3': 4, 'x1y0': 3, 'x1y1': 4, 'x1y2': 1, 'x1y3': 2, 'x2y0': 4, 'x2y1': 1, 'x2y2': 2, 'x2y3': 3, 'x3y0': 2, 'x3y1': 3, 'x3y2': 4, 'x3y3': 1}
[[1 2 3 4]
 [3 4 1 2]
 [4 1 2 3]
 [2 3 4 1]]
[[1 2 3 4]
 [3 4 1 2]
 [4 1 2 3]
 [2 3 4 1]]
